<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="STDEV009" failures="0" tests="4" name="com.crossjourney.testcases.LoginPageTest" time="0.030" errors="1" timestamp="22 Jul 2023 10:27:13 GMT" skipped="3">
  <testcase classname="com.crossjourney.testcases.LoginPageTest" name="setUp" time="0.030">
    <error message="Cannot invoke &quot;java.util.Properties.getProperty(String)&quot; because &quot;com.crossjourney.base.TestBase.prop&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "com.crossjourney.base.TestBase.prop" is null
at com.crossjourney.base.TestBase.initialization(TestBase.java:37)
at com.crossjourney.testcases.LoginPageTest.setUp(LoginPageTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase classname="com.crossjourney.testcases.LoginPageTest" name="testIcon" time="0.000">
    <skipped/>
  </testcase> <!-- testIcon -->
  <testcase classname="com.crossjourney.testcases.LoginPageTest" name="verifyLoginLabel" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLoginLabel -->
  <testcase classname="com.crossjourney.testcases.LoginPageTest" name="verifyPageTitle" time="0.000">
    <skipped/>
  </testcase> <!-- verifyPageTitle -->
</testsuite> <!-- com.crossjourney.testcases.LoginPageTest -->
